### PR TITLE
add h2 at the end by Gowri

### PR DESCRIPTION
**Pull request by Gowrisdev**
Hi Prasana, i have added h2 tag at the end  of the footer

### CODE REVIEW

**Review by prasanakprasad — COMMENTED** [review]
Hi Gowri,
Looks good.

**Comment by Gowrisdev** [comment]
This is Gowri, thanks for the review Prasana

**Review by mackay999 — APPROVED** [review]

**Review by PrameelaGit — COMMENTED** [review]
All looking good

**Comment by PrameelaGit** [comment]
Merged by Prameela

**Pull request merged**
